/** Generated by scripts/prepare_images.py — crop sizes and highlight boxes (fractions of each crop). */
export type Box = [number, number, number, number];
export const ARCHIVE = {
  title: { w: 1500, h: 239 },
  summary: { w: 1100, h: 442 },
  naming: { w: 1100, h: 353 },
  fig9: { w: 900, h: 690 },
  fig7: { w: 800, h: 656 },
  fig2: { w: 800, h: 896 },
  portrait: { w: 280, h: 396 },
};
export const SUMMARY_MARKS: Record<'weight' | 'fat' | 'arthritis' | 'villi', Box[]> = {
  weight: [[0.8839, 0.0112, 0.0959, 0.1231], [0.0142, 0.1231, 0.5281, 0.1231]],
  fat: [[0.5468, 0.1231, 0.4337, 0.1231], [0.015, 0.2351, 0.433, 0.1194]],
  arthritis: [[0.015, 0.3433, 0.43, 0.1231]],
  villi: [[0.3551, 0.7817, 0.6232, 0.1231], [0.0142, 0.8937, 0.3633, 0.1007]],
};
export const NAMING_MARKS: Record<'term' | 'noName', Box[]> = {
  term: [[0.3097, 0.4442, 0.4109, 0.1359]],
  noName: [[0.8078, 0.1553, 0.1805, 0.1286], [0.0093, 0.3034, 0.979, 0.1359], [0.0078, 0.4563, 0.0981, 0.1141]],
};
