"""Prepare archival images for the exhibit (run once; outputs are committed).

Sources (public domain, see CREDITS.md):
  * Whipple GH. Bulletin of the Johns Hopkins Hospital 18(198):382-391, Sept 1907.
    Scan: Internet Archive item sim_johns-hopkins-medical-journal_1907-09_18_198 (JP2 leaves 71, 80, 82, 84).
  * George Hoyt Whipple, 1934 Nobel portrait (Wikimedia Commons "George Whipple nobel.jpg", PD-Sweden / PD-1996).

Usage: python scripts/prepare_images.py <dir with leaf JP2s + whipple_nobel.jpg>
Crops are given in full-resolution scan pixels (from the IA hOCR word boxes).
"""
import json
import sys
from pathlib import Path

from PIL import Image, ImageFilter, ImageOps

Image.MAX_IMAGE_PIXELS = None
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
OUT = Path(__file__).resolve().parents[1] / "public" / "archive"
OUT.mkdir(parents=True, exist_ok=True)
LEAF = "sim_johns-hopkins-medical-journal_1907-09_18_198_{:04d}.jp2"


def leaf(n, rotate=0):
    im = Image.open(SRC / "pages" / LEAF.format(n)).convert("L")
    if rotate:
        im = im.rotate(rotate, expand=True)
    return im


def clean_text(im):
    """Lift paper to white and deepen ink so the crop can be multiplied onto a paper texture."""
    im = ImageOps.autocontrast(im, cutoff=(1, 2))
    lut = [0 if v < 40 else 255 if v > 205 else int((v - 40) / 165 * 255) for v in range(256)]
    return im.point(lut)


def save(im, name, width, quality=82):
    if im.width > width:
        im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
    p = OUT / f"{name}.webp"
    im.save(p, "WEBP", quality=quality, method=6)
    print(f"{p.name}: {im.size} {p.stat().st_size // 1024} KB")
    return im.size


meta = {}

# --- p. 382: title block and the opening summary paragraph -----------------------------------
p382 = leaf(71)
title = clean_text(p382.crop((290, 1040, 2990, 1470)))
meta["title"] = save(title, "whipple1907-title", 1500)

summary_box = (290, 1480, 1625, 2016)
summary = clean_text(p382.crop(summary_box))
meta["summary"] = save(summary, "whipple1907-summary", 1100)
sx0, sy0 = summary_box[0], summary_box[1]
sw, sh = summary_box[2] - summary_box[0], summary_box[3] - summary_box[1]


def rel(boxes, ox, oy, w, h):
    return [[round((x0 - ox) / w, 4), round((y0 - oy) / h, 4), round((x1 - x0) / w, 4), round((y1 - y0) / h, 4)]
            for x0, y0, x1, y1 in boxes]


# highlight rectangles as fractions of the crop (x, y, w, h), padded slightly
pad = 6
highlights = {
    "weight": [(1476, 1492, 1592, 1546), (315, 1552, 1008, 1606)],
    "fat": [(1026, 1552, 1593, 1606), (316, 1612, 882, 1664)],
    "arthritis": [(316, 1670, 878, 1724)],
    "villi": [(770, 1905, 1590, 1959), (315, 1965, 788, 2007)],
}
meta["summaryHighlights"] = {k: rel([(a - pad, b - pad, c + pad, d + pad) for a, b, c, d in v], sx0, sy0, sw, sh)
                             for k, v in highlights.items()}

# --- p. 391: the naming paragraph ------------------------------------------------------------
p391 = leaf(84)
naming_box = (190, 680, 1475, 1092)
naming = clean_text(p391.crop(naming_box))
meta["naming"] = save(naming, "whipple1907-naming", 1100)
nx0, ny0 = naming_box[0], naming_box[1]
nw, nh = naming_box[2] - naming_box[0], naming_box[3] - naming_box[1]
meta["namingHighlights"] = {
    "term": rel([(588, 863, 1116, 919)], nx0, ny0, nw, nh),
    "noName": rel([(1228, 744, 1460, 797), (202, 805, 1460, 861), (200, 868, 326, 915)], nx0, ny0, nw, nh),
}

# --- Plate XXXV fig. 9 (rod-shaped organism) and fig. 7; Plate XXXIII fig. 2 ------------------
s82 = 1 / 0.2455795677799607
plate35 = leaf(82, rotate=-90)
fig9 = plate35.crop(tuple(round(v * s82) for v in (545, 393, 922, 682)))
meta["fig9"] = save(ImageOps.autocontrast(fig9, cutoff=0.5), "whipple1907-fig9", 900, 80)
fig7 = plate35.crop(tuple(round(v * s82) for v in (354, 40, 655, 287)))
meta["fig7"] = save(ImageOps.autocontrast(fig7, cutoff=0.5), "whipple1907-fig7", 800, 80)

s80 = 1 / 0.24509803921568626
plate33 = leaf(80, rotate=-90)
fig2 = plate33.crop(tuple(round(v * s80) for v in (88, 343, 395, 687)))
meta["fig2"] = save(ImageOps.autocontrast(fig2, cutoff=0.5), "whipple1907-fig2", 800, 80)

# --- Portrait ---------------------------------------------------------------------------------
portrait = Image.open(SRC / "whipple_nobel.jpg").convert("L")
meta["portrait"] = save(ImageOps.autocontrast(portrait, cutoff=0.3), "whipple-portrait-1934", 280, 88)

ts = [
    "/** Generated by scripts/prepare_images.py — crop sizes and highlight boxes (fractions of each crop). */",
    "export type Box = [number, number, number, number];",
    "export const ARCHIVE = {",
]
for k in ["title", "summary", "naming", "fig9", "fig7", "fig2", "portrait"]:
    ts.append(f"  {k}: {{ w: {meta[k][0]}, h: {meta[k][1]} }},")
ts.append("};")


def boxes(v):
    return ", ".join("[" + ", ".join(str(n) for n in b) + "]" for b in v)


ts.append("export const SUMMARY_MARKS: Record<'weight' | 'fat' | 'arthritis' | 'villi', Box[]> = {")
ts += [f"  {k}: [{boxes(v)}]," for k, v in meta["summaryHighlights"].items()]
ts.append("};")
ts.append("export const NAMING_MARKS: Record<'term' | 'noName', Box[]> = {")
ts += [f"  {k}: [{boxes(v)}]," for k, v in meta["namingHighlights"].items()]
ts.append("};")
dst = Path(__file__).resolve().parents[1] / "src" / "content" / "archive.ts"
dst.write_text(chr(10).join(ts) + chr(10), encoding="utf-8")
print("wrote", dst)
